title: <p align="center"> Titi Pudjiastuti </p>

logo: "/images/new profile.png?raw=true" # your photo (or logo) here

description:
  <p align="center">
  <a href=[![Kaggle](https://img.shields.io/badge/Kaggle-035a7d?style=for-the-badge&logo=kaggle&logoColor=white)](https://www.kaggle.com/upperadd)></a> |
  <a href="https://www.linkedin.com//in/titi-p-268161243/">LinkedIn</a> |
  <a href="https://github.com/upperAdd">Github</a>
  </p>
  
  <p align="justify">
  Welcome to Titi's portofolio site. This page still working on progress to represent what had been doing so far to have a career-changing in data science.
  <br><br>
  I hope you enjoy seeing Titi's progress and effort through her Github page while this portfolio on progress. Titi's look forward to any feedback to help her improve her skills.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
