title: <p align="center"> Titi Pudjiastuti </p>

logo: "/images/new profile.png?raw=true"  # your photo (or logo) here

description:
  <p align="center">
  <a href="https://www.kaggle.com/upperadd">Kaggle</a> |
  <a href="https://www.linkedin.com//in/titi-p-268161243/">LinkedIn</a> |
  <a href="https://github.com/upperAdd">Github</a>
  </p>
  
  <p align="justify"> Welcome to Titi's portofolio. As aspiring data scientist, you can find more information about me through my projects.
  <br><br>
  On this page are most of the projects I learned through bootcamps or self–taught using programming language and software to interpret, analyse and visualise data. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-238191394-1 # your Google Analytics tracking ID here
