title: Titi Pudjiastuti # your name (or website title) here
logo: "/images/new profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to Titi's portofolio site. This page still working on progress to represent what had been doing so far to have a career-changing in data science.
  <br><br>
  I hope you enjoy seeing Titi's progress and effort through her Github page while this portfolio on progress. Titi's look forward to any feedback to help her improve her skills.
  <br><br>
  <a href="https://www.kaggle.com/upperadd">View My Kaggle Profile</a> 
  
  <a href="https://www.linkedin.com/in/titi-p-268161243/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
